<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ["id" => 1, "name" => "Default", "alpha_code2" => "AA", "alpha_code3" => "AAA", "numeric_code" => "000", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 2, "name" => "Afghanistan", "alpha_code2" => "AF", "alpha_code3" => "AFG", "numeric_code" => "004", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 3, "name" => "Albania", "alpha_code2" => "AL", "alpha_code3" => "ALB", "numeric_code" => "008", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 4, "name" => "Algeria", "alpha_code2" => "DZ", "alpha_code3" => "DZA", "numeric_code" => "012", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 5, "name" => "American Samoa", "alpha_code2" => "AS", "alpha_code3" => "ASM", "numeric_code" => "016", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 6, "name" => "Andorra", "alpha_code2" => "AD", "alpha_code3" => "AND", "numeric_code" => "020", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 7, "name" => "Angola", "alpha_code2" => "AO", "alpha_code3" => "AGO", "numeric_code" => "024", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 8, "name" => "Anguilla", "alpha_code2" => "AI", "alpha_code3" => "AIA", "numeric_code" => "660", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 9, "name" => "Antarctica", "alpha_code2" => "AQ", "alpha_code3" => "ATA", "numeric_code" => "010", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 10, "name" => "Antigua and Barbuda", "alpha_code2" => "AG", "alpha_code3" => "ATG", "numeric_code" => "028", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 11, "name" => "Argentina", "alpha_code2" => "AR", "alpha_code3" => "ARG", "numeric_code" => "032", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 12, "name" => "Armenia", "alpha_code2" => "AM", "alpha_code3" => "ARM", "numeric_code" => "051", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 13, "name" => "Aruba", "alpha_code2" => "AW", "alpha_code3" => "ABW", "numeric_code" => "533", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 14, "name" => "Australia", "alpha_code2" => "AU", "alpha_code3" => "AUS", "numeric_code" => "036", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 15, "name" => "Austria", "alpha_code2" => "AT", "alpha_code3" => "AUT", "numeric_code" => "040", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 16, "name" => "Azerbaijan", "alpha_code2" => "AZ", "alpha_code3" => "AZE", "numeric_code" => "031", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 17, "name" => "Bahamas", "alpha_code2" => "BS", "alpha_code3" => "BHS", "numeric_code" => "044", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 18, "name" => "Bahrain", "alpha_code2" => "BH", "alpha_code3" => "BHR", "numeric_code" => "048", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 19, "name" => "Bangladesh", "alpha_code2" => "BD", "alpha_code3" => "BGD", "numeric_code" => "050", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 20, "name" => "Barbados", "alpha_code2" => "BB", "alpha_code3" => "BRB", "numeric_code" => "052", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 21, "name" => "Belarus", "alpha_code2" => "BY", "alpha_code3" => "BLR", "numeric_code" => "112", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 22, "name" => "Belgium", "alpha_code2" => "BE", "alpha_code3" => "BEL", "numeric_code" => "056", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 23, "name" => "Belize", "alpha_code2" => "BZ", "alpha_code3" => "BLZ", "numeric_code" => "084", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 24, "name" => "Benin", "alpha_code2" => "BJ", "alpha_code3" => "BEN", "numeric_code" => "204", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 25, "name" => "Bermuda", "alpha_code2" => "BM", "alpha_code3" => "BMU", "numeric_code" => "060", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 26, "name" => "Bhutan", "alpha_code2" => "BT", "alpha_code3" => "BTN", "numeric_code" => "064", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 27, "name" => "Bolivia (Plurinational State of)", "alpha_code2" => "BO", "alpha_code3" => "BOL", "numeric_code" => "068", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 28, "name" => "Bonaire, Sint Eustatius and Saba", "alpha_code2" => "BQ", "alpha_code3" => "BES", "numeric_code" => "535", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 29, "name" => "Bosnia and Herzegovina", "alpha_code2" => "BA", "alpha_code3" => "BIH", "numeric_code" => "070", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 30, "name" => "Botswana", "alpha_code2" => "BW", "alpha_code3" => "BWA", "numeric_code" => "072", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 31, "name" => "Bouvet Island", "alpha_code2" => "BV", "alpha_code3" => "BVT", "numeric_code" => "074", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 32, "name" => "Brazil", "alpha_code2" => "BR", "alpha_code3" => "BRA", "numeric_code" => "076", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 33, "name" => "British Indian Ocean Territory", "alpha_code2" => "IO", "alpha_code3" => "IOT", "numeric_code" => "086", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 34, "name" => "Brunei Darussalam", "alpha_code2" => "BN", "alpha_code3" => "BRN", "numeric_code" => "096", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 35, "name" => "Bulgaria", "alpha_code2" => "BG", "alpha_code3" => "BGR", "numeric_code" => "100", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 36, "name" => "Burkina Faso", "alpha_code2" => "BF", "alpha_code3" => "BFA", "numeric_code" => "854", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 37, "name" => "Burundi", "alpha_code2" => "BI", "alpha_code3" => "BDI", "numeric_code" => "108", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 38, "name" => "Cabo Verde", "alpha_code2" => "CV", "alpha_code3" => "CPV", "numeric_code" => "132", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 39, "name" => "Cambodia", "alpha_code2" => "KH", "alpha_code3" => "KHM", "numeric_code" => "116", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 40, "name" => "Cameroon", "alpha_code2" => "CM", "alpha_code3" => "CMR", "numeric_code" => "120", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 41, "name" => "Canada", "alpha_code2" => "CA", "alpha_code3" => "CAN", "numeric_code" => "124", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 42, "name" => "Cayman Islands", "alpha_code2" => "KY", "alpha_code3" => "CYM", "numeric_code" => "136", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 43, "name" => "Central African Republic", "alpha_code2" => "CF", "alpha_code3" => "CAF", "numeric_code" => "140", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 44, "name" => "Chad", "alpha_code2" => "TD", "alpha_code3" => "TCD", "numeric_code" => "148", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 45, "name" => "Chile", "alpha_code2" => "CL", "alpha_code3" => "CHL", "numeric_code" => "152", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 46, "name" => "China", "alpha_code2" => "CN", "alpha_code3" => "CHN", "numeric_code" => "156", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 47, "name" => "Christmas Island", "alpha_code2" => "CX", "alpha_code3" => "CXR", "numeric_code" => "162", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 48, "name" => "Cocos (Keeling) Islands", "alpha_code2" => "CC", "alpha_code3" => "CCK", "numeric_code" => "166", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 49, "name" => "Colombia", "alpha_code2" => "CO", "alpha_code3" => "COL", "numeric_code" => "170", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 50, "name" => "Comoros", "alpha_code2" => "KM", "alpha_code3" => "COM", "numeric_code" => "174", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 51, "name" => "Congo (the Democratic Republic of the)", "alpha_code2" => "CD", "alpha_code3" => "COD", "numeric_code" => "180", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 52, "name" => "Congo", "alpha_code2" => "CG", "alpha_code3" => "COG", "numeric_code" => "178", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 53, "name" => "Cook Islands", "alpha_code2" => "CK", "alpha_code3" => "COK", "numeric_code" => "184", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 54, "name" => "Costa Rica", "alpha_code2" => "CR", "alpha_code3" => "CRI", "numeric_code" => "188", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 55, "name" => "Croatia", "alpha_code2" => "HR", "alpha_code3" => "HRV", "numeric_code" => "191", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 56, "name" => "Cuba", "alpha_code2" => "CU", "alpha_code3" => "CUB", "numeric_code" => "192", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 57, "name" => "Curaçao", "alpha_code2" => "CW", "alpha_code3" => "CUW", "numeric_code" => "531", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 58, "name" => "Cyprus", "alpha_code2" => "CY", "alpha_code3" => "CYP", "numeric_code" => "196", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 59, "name" => "Czechia", "alpha_code2" => "CZ", "alpha_code3" => "CZE", "numeric_code" => "203", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 60, "name" => "Côte d'Ivoire", "alpha_code2" => "CI", "alpha_code3" => "CIV", "numeric_code" => "384", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 61, "name" => "Denmark", "alpha_code2" => "DK", "alpha_code3" => "DNK", "numeric_code" => "208", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 62, "name" => "Djibouti", "alpha_code2" => "DJ", "alpha_code3" => "DJI", "numeric_code" => "262", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 63, "name" => "Dominica", "alpha_code2" => "DM", "alpha_code3" => "DMA", "numeric_code" => "212", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 64, "name" => "Dominican Republic", "alpha_code2" => "DO", "alpha_code3" => "DOM", "numeric_code" => "214", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 65, "name" => "Ecuador", "alpha_code2" => "EC", "alpha_code3" => "ECU", "numeric_code" => "218", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 66, "name" => "Egypt", "alpha_code2" => "EG", "alpha_code3" => "EGY", "numeric_code" => "818", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 67, "name" => "El Salvador", "alpha_code2" => "SV", "alpha_code3" => "SLV", "numeric_code" => "222", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 68, "name" => "Equatorial Guinea", "alpha_code2" => "GQ", "alpha_code3" => "GNQ", "numeric_code" => "226", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 69, "name" => "Eritrea", "alpha_code2" => "ER", "alpha_code3" => "ERI", "numeric_code" => "232", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 70, "name" => "Estonia", "alpha_code2" => "EE", "alpha_code3" => "EST", "numeric_code" => "233", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 71, "name" => "Eswatini", "alpha_code2" => "SZ", "alpha_code3" => "SWZ", "numeric_code" => "748", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 72, "name" => "Ethiopia", "alpha_code2" => "ET", "alpha_code3" => "ETH", "numeric_code" => "231", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 73, "name" => "Falkland Islands [Malvinas]", "alpha_code2" => "FK", "alpha_code3" => "FLK", "numeric_code" => "238", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 74, "name" => "Faroe Islands", "alpha_code2" => "FO", "alpha_code3" => "FRO", "numeric_code" => "234", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 75, "name" => "Fiji", "alpha_code2" => "FJ", "alpha_code3" => "FJI", "numeric_code" => "242", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 76, "name" => "Finland", "alpha_code2" => "FI", "alpha_code3" => "FIN", "numeric_code" => "246", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 77, "name" => "France", "alpha_code2" => "FR", "alpha_code3" => "FRA", "numeric_code" => "250", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 78, "name" => "French Guiana", "alpha_code2" => "GF", "alpha_code3" => "GUF", "numeric_code" => "254", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 79, "name" => "French Polynesia", "alpha_code2" => "PF", "alpha_code3" => "PYF", "numeric_code" => "258", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 80, "name" => "French Southern Territories", "alpha_code2" => "TF", "alpha_code3" => "ATF", "numeric_code" => "260", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 81, "name" => "Gabon", "alpha_code2" => "GA", "alpha_code3" => "GAB", "numeric_code" => "266", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 82, "name" => "Gambia", "alpha_code2" => "GM", "alpha_code3" => "GMB", "numeric_code" => "270", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 83, "name" => "Georgia", "alpha_code2" => "GE", "alpha_code3" => "GEO", "numeric_code" => "268", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 84, "name" => "Germany", "alpha_code2" => "DE", "alpha_code3" => "DEU", "numeric_code" => "276", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 85, "name" => "Ghana", "alpha_code2" => "GH", "alpha_code3" => "GHA", "numeric_code" => "288", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 86, "name" => "Gibraltar", "alpha_code2" => "GI", "alpha_code3" => "GIB", "numeric_code" => "292", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 87, "name" => "Greece", "alpha_code2" => "GR", "alpha_code3" => "GRC", "numeric_code" => "300", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 88, "name" => "Greenland", "alpha_code2" => "GL", "alpha_code3" => "GRL", "numeric_code" => "304", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 89, "name" => "Grenada", "alpha_code2" => "GD", "alpha_code3" => "GRD", "numeric_code" => "308", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 90, "name" => "Guadeloupe", "alpha_code2" => "GP", "alpha_code3" => "GLP", "numeric_code" => "312", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 91, "name" => "Guam", "alpha_code2" => "GU", "alpha_code3" => "GUM", "numeric_code" => "316", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 92, "name" => "Guatemala", "alpha_code2" => "GT", "alpha_code3" => "GTM", "numeric_code" => "320", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 93, "name" => "Guernsey", "alpha_code2" => "GG", "alpha_code3" => "GGY", "numeric_code" => "831", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 94, "name" => "Guinea", "alpha_code2" => "GN", "alpha_code3" => "GIN", "numeric_code" => "324", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 95, "name" => "Guinea-Bissau", "alpha_code2" => "GW", "alpha_code3" => "GNB", "numeric_code" => "624", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 96, "name" => "Guyana", "alpha_code2" => "GY", "alpha_code3" => "GUY", "numeric_code" => "328", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 97, "name" => "Haiti", "alpha_code2" => "HT", "alpha_code3" => "HTI", "numeric_code" => "332", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 98, "name" => "Heard Island and McDonald Islands", "alpha_code2" => "HM", "alpha_code3" => "HMD", "numeric_code" => "334", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 99, "name" => "Holy See", "alpha_code2" => "VA", "alpha_code3" => "VAT", "numeric_code" => "336", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 100, "name" => "Honduras", "alpha_code2" => "HN", "alpha_code3" => "HND", "numeric_code" => "340", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 101, "name" => "Hong Kong", "alpha_code2" => "HK", "alpha_code3" => "HKG", "numeric_code" => "344", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 102, "name" => "Hungary", "alpha_code2" => "HU", "alpha_code3" => "HUN", "numeric_code" => "348", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 103, "name" => "Iceland", "alpha_code2" => "IS", "alpha_code3" => "ISL", "numeric_code" => "352", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 104, "name" => "India", "alpha_code2" => "IN", "alpha_code3" => "IND", "numeric_code" => "356", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 105, "name" => "Indonesia", "alpha_code2" => "ID", "alpha_code3" => "IDN", "numeric_code" => "360", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 106, "name" => "Iran (Islamic Republic of)", "alpha_code2" => "IR", "alpha_code3" => "IRN", "numeric_code" => "364", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 107, "name" => "Iraq", "alpha_code2" => "IQ", "alpha_code3" => "IRQ", "numeric_code" => "368", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 108, "name" => "Ireland", "alpha_code2" => "IE", "alpha_code3" => "IRL", "numeric_code" => "372", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 109, "name" => "Isle of Man", "alpha_code2" => "IM", "alpha_code3" => "IMN", "numeric_code" => "833", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 110, "name" => "Israel", "alpha_code2" => "IL", "alpha_code3" => "ISR", "numeric_code" => "376", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 111, "name" => "Italy", "alpha_code2" => "IT", "alpha_code3" => "ITA", "numeric_code" => "380", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 112, "name" => "Jamaica", "alpha_code2" => "JM", "alpha_code3" => "JAM", "numeric_code" => "388", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 113, "name" => "Japan", "alpha_code2" => "JP", "alpha_code3" => "JPN", "numeric_code" => "392", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 114, "name" => "Jersey", "alpha_code2" => "JE", "alpha_code3" => "JEY", "numeric_code" => "832", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 115, "name" => "Jordan", "alpha_code2" => "JO", "alpha_code3" => "JOR", "numeric_code" => "400", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 116, "name" => "Kazakhstan", "alpha_code2" => "KZ", "alpha_code3" => "KAZ", "numeric_code" => "398", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 117, "name" => "Kenya", "alpha_code2" => "KE", "alpha_code3" => "KEN", "numeric_code" => "404", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 118, "name" => "Kiribati", "alpha_code2" => "KI", "alpha_code3" => "KIR", "numeric_code" => "296", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 119, "name" => "Korea (the Democratic People's Republic of)", "alpha_code2" => "KP", "alpha_code3" => "PRK", "numeric_code" => "408", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 120, "name" => "Korea (the Republic of)", "alpha_code2" => "KR", "alpha_code3" => "KOR", "numeric_code" => "410", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 121, "name" => "Kuwait", "alpha_code2" => "KW", "alpha_code3" => "KWT", "numeric_code" => "414", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 122, "name" => "Kyrgyzstan", "alpha_code2" => "KG", "alpha_code3" => "KGZ", "numeric_code" => "417", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 123, "name" => "Lao People's Democratic Republic", "alpha_code2" => "LA", "alpha_code3" => "LAO", "numeric_code" => "418", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 124, "name" => "Latvia", "alpha_code2" => "LV", "alpha_code3" => "LVA", "numeric_code" => "428", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 125, "name" => "Lebanon", "alpha_code2" => "LB", "alpha_code3" => "LBN", "numeric_code" => "422", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 126, "name" => "Lesotho", "alpha_code2" => "LS", "alpha_code3" => "LSO", "numeric_code" => "426", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 127, "name" => "Liberia", "alpha_code2" => "LR", "alpha_code3" => "LBR", "numeric_code" => "430", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 128, "name" => "Libya", "alpha_code2" => "LY", "alpha_code3" => "LBY", "numeric_code" => "434", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 129, "name" => "Liechtenstein", "alpha_code2" => "LI", "alpha_code3" => "LIE", "numeric_code" => "438", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 130, "name" => "Lithuania", "alpha_code2" => "LT", "alpha_code3" => "LTU", "numeric_code" => "440", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 131, "name" => "Luxembourg", "alpha_code2" => "LU", "alpha_code3" => "LUX", "numeric_code" => "442", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 132, "name" => "Macao", "alpha_code2" => "MO", "alpha_code3" => "MAC", "numeric_code" => "446", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 133, "name" => "Madagascar", "alpha_code2" => "MG", "alpha_code3" => "MDG", "numeric_code" => "450", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 134, "name" => "Malawi", "alpha_code2" => "MW", "alpha_code3" => "MWI", "numeric_code" => "454", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 135, "name" => "Malaysia", "alpha_code2" => "MY", "alpha_code3" => "MYS", "numeric_code" => "458", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 136, "name" => "Maldives", "alpha_code2" => "MV", "alpha_code3" => "MDV", "numeric_code" => "462", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 137, "name" => "Mali", "alpha_code2" => "ML", "alpha_code3" => "MLI", "numeric_code" => "466", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 138, "name" => "Malta", "alpha_code2" => "MT", "alpha_code3" => "MLT", "numeric_code" => "470", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 139, "name" => "Marshall Islands", "alpha_code2" => "MH", "alpha_code3" => "MHL", "numeric_code" => "584", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 140, "name" => "Martinique", "alpha_code2" => "MQ", "alpha_code3" => "MTQ", "numeric_code" => "474", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 141, "name" => "Mauritania", "alpha_code2" => "MR", "alpha_code3" => "MRT", "numeric_code" => "478", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 142, "name" => "Mauritius", "alpha_code2" => "MU", "alpha_code3" => "MUS", "numeric_code" => "480", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 143, "name" => "Mayotte", "alpha_code2" => "YT", "alpha_code3" => "MYT", "numeric_code" => "175", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 144, "name" => "Mexico", "alpha_code2" => "MX", "alpha_code3" => "MEX", "numeric_code" => "484", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 145, "name" => "Micronesia (Federated States of)", "alpha_code2" => "FM", "alpha_code3" => "FSM", "numeric_code" => "583", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 146, "name" => "Moldova (the Republic of)", "alpha_code2" => "MD", "alpha_code3" => "MDA", "numeric_code" => "498", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 147, "name" => "Monaco", "alpha_code2" => "MC", "alpha_code3" => "MCO", "numeric_code" => "492", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 148, "name" => "Mongolia", "alpha_code2" => "MN", "alpha_code3" => "MNG", "numeric_code" => "496", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 149, "name" => "Montenegro", "alpha_code2" => "ME", "alpha_code3" => "MNE", "numeric_code" => "499", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 150, "name" => "Montserrat", "alpha_code2" => "MS", "alpha_code3" => "MSR", "numeric_code" => "500", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 151, "name" => "Morocco", "alpha_code2" => "MA", "alpha_code3" => "MAR", "numeric_code" => "504", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 152, "name" => "Mozambique", "alpha_code2" => "MZ", "alpha_code3" => "MOZ", "numeric_code" => "508", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 153, "name" => "Myanmar", "alpha_code2" => "MM", "alpha_code3" => "MMR", "numeric_code" => "104", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 154, "name" => "Namibia", "alpha_code2" => "NA", "alpha_code3" => "NAM", "numeric_code" => "516", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 155, "name" => "Nauru", "alpha_code2" => "NR", "alpha_code3" => "NRU", "numeric_code" => "520", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 156, "name" => "Nepal", "alpha_code2" => "NP", "alpha_code3" => "NPL", "numeric_code" => "524", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 157, "name" => "Netherlands", "alpha_code2" => "NL", "alpha_code3" => "NLD", "numeric_code" => "528", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 158, "name" => "New Caledonia", "alpha_code2" => "NC", "alpha_code3" => "NCL", "numeric_code" => "540", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 159, "name" => "New Zealand", "alpha_code2" => "NZ", "alpha_code3" => "NZL", "numeric_code" => "554", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 160, "name" => "Nicaragua", "alpha_code2" => "NI", "alpha_code3" => "NIC", "numeric_code" => "558", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 161, "name" => "Niger", "alpha_code2" => "NE", "alpha_code3" => "NER", "numeric_code" => "562", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 162, "name" => "Nigeria", "alpha_code2" => "NG", "alpha_code3" => "NGA", "numeric_code" => "566", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 163, "name" => "Niue", "alpha_code2" => "NU", "alpha_code3" => "NIU", "numeric_code" => "570", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 164, "name" => "Norfolk Island", "alpha_code2" => "NF", "alpha_code3" => "NFK", "numeric_code" => "574", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 165, "name" => "Northern Mariana Islands", "alpha_code2" => "MP", "alpha_code3" => "MNP", "numeric_code" => "580", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 166, "name" => "Norway", "alpha_code2" => "NO", "alpha_code3" => "NOR", "numeric_code" => "578", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 167, "name" => "Oman", "alpha_code2" => "OM", "alpha_code3" => "OMN", "numeric_code" => "512", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 168, "name" => "Pakistan", "alpha_code2" => "PK", "alpha_code3" => "PAK", "numeric_code" => "586", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 169, "name" => "Palau", "alpha_code2" => "PW", "alpha_code3" => "PLW", "numeric_code" => "585", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 170, "name" => "Palestine, State of", "alpha_code2" => "PS", "alpha_code3" => "PSE", "numeric_code" => "275", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 171, "name" => "Panama", "alpha_code2" => "PA", "alpha_code3" => "PAN", "numeric_code" => "591", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 172, "name" => "Papua New Guinea", "alpha_code2" => "PG", "alpha_code3" => "PNG", "numeric_code" => "598", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 173, "name" => "Paraguay", "alpha_code2" => "PY", "alpha_code3" => "PRY", "numeric_code" => "600", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 174, "name" => "Peru", "alpha_code2" => "PE", "alpha_code3" => "PER", "numeric_code" => "604", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 175, "name" => "Philippines", "alpha_code2" => "PH", "alpha_code3" => "PHL", "numeric_code" => "608", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 176, "name" => "Pitcairn", "alpha_code2" => "PN", "alpha_code3" => "PCN", "numeric_code" => "612", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 177, "name" => "Poland", "alpha_code2" => "PL", "alpha_code3" => "POL", "numeric_code" => "616", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 178, "name" => "Portugal", "alpha_code2" => "PT", "alpha_code3" => "PRT", "numeric_code" => "620", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 179, "name" => "Puerto Rico", "alpha_code2" => "PR", "alpha_code3" => "PRI", "numeric_code" => "630", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 180, "name" => "Qatar", "alpha_code2" => "QA", "alpha_code3" => "QAT", "numeric_code" => "634", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 181, "name" => "Republic of North Macedonia", "alpha_code2" => "MK", "alpha_code3" => "MKD", "numeric_code" => "807", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 182, "name" => "Romania", "alpha_code2" => "RO", "alpha_code3" => "ROU", "numeric_code" => "642", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 183, "name" => "Russian Federation", "alpha_code2" => "RU", "alpha_code3" => "RUS", "numeric_code" => "643", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 184, "name" => "Rwanda", "alpha_code2" => "RW", "alpha_code3" => "RWA", "numeric_code" => "646", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 185, "name" => "Réunion", "alpha_code2" => "RE", "alpha_code3" => "REU", "numeric_code" => "638", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 186, "name" => "Saint Barthélemy", "alpha_code2" => "BL", "alpha_code3" => "BLM", "numeric_code" => "652", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 187, "name" => "Saint Helena, Ascension and Tristan da Cunha", "alpha_code2" => "SH", "alpha_code3" => "SHN", "numeric_code" => "654", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 188, "name" => "Saint Kitts and Nevis", "alpha_code2" => "KN", "alpha_code3" => "KNA", "numeric_code" => "659", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 189, "name" => "Saint Lucia", "alpha_code2" => "LC", "alpha_code3" => "LCA", "numeric_code" => "662", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 190, "name" => "Saint Martin (French part)", "alpha_code2" => "MF", "alpha_code3" => "MAF", "numeric_code" => "663", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 191, "name" => "Saint Pierre and Miquelon", "alpha_code2" => "PM", "alpha_code3" => "SPM", "numeric_code" => "666", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 192, "name" => "Saint Vincent and the Grenadines", "alpha_code2" => "VC", "alpha_code3" => "VCT", "numeric_code" => "670", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 193, "name" => "Samoa", "alpha_code2" => "WS", "alpha_code3" => "WSM", "numeric_code" => "882", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 194, "name" => "San Marino", "alpha_code2" => "SM", "alpha_code3" => "SMR", "numeric_code" => "674", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 195, "name" => "Sao Tome and Principe", "alpha_code2" => "ST", "alpha_code3" => "STP", "numeric_code" => "678", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 196, "name" => "Saudi Arabia", "alpha_code2" => "SA", "alpha_code3" => "SAU", "numeric_code" => "682", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 197, "name" => "Senegal", "alpha_code2" => "SN", "alpha_code3" => "SEN", "numeric_code" => "686", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 198, "name" => "Serbia", "alpha_code2" => "RS", "alpha_code3" => "SRB", "numeric_code" => "688", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 199, "name" => "Seychelles", "alpha_code2" => "SC", "alpha_code3" => "SYC", "numeric_code" => "690", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 200, "name" => "Sierra Leone", "alpha_code2" => "SL", "alpha_code3" => "SLE", "numeric_code" => "694", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 201, "name" => "Singapore", "alpha_code2" => "SG", "alpha_code3" => "SGP", "numeric_code" => "702", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 202, "name" => "Sint Maarten (Dutch part)", "alpha_code2" => "SX", "alpha_code3" => "SXM", "numeric_code" => "534", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 203, "name" => "Slovakia", "alpha_code2" => "SK", "alpha_code3" => "SVK", "numeric_code" => "703", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 204, "name" => "Slovenia", "alpha_code2" => "SI", "alpha_code3" => "SVN", "numeric_code" => "705", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 205, "name" => "Solomon Islands", "alpha_code2" => "SB", "alpha_code3" => "SLB", "numeric_code" => "090", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 206, "name" => "Somalia", "alpha_code2" => "SO", "alpha_code3" => "SOM", "numeric_code" => "706", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 207, "name" => "South Africa", "alpha_code2" => "ZA", "alpha_code3" => "ZAF", "numeric_code" => "710", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 208, "name" => "South Georgia and the South Sandwich Islands", "alpha_code2" => "GS", "alpha_code3" => "SGS", "numeric_code" => "239", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 209, "name" => "South Sudan", "alpha_code2" => "SS", "alpha_code3" => "SSD", "numeric_code" => "728", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 210, "name" => "Spain", "alpha_code2" => "ES", "alpha_code3" => "ESP", "numeric_code" => "724", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 211, "name" => "Sri Lanka", "alpha_code2" => "LK", "alpha_code3" => "LKA", "numeric_code" => "144", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 212, "name" => "Sudan", "alpha_code2" => "SD", "alpha_code3" => "SDN", "numeric_code" => "729", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 213, "name" => "Suriname", "alpha_code2" => "SR", "alpha_code3" => "SUR", "numeric_code" => "740", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 214, "name" => "Svalbard and Jan Mayen", "alpha_code2" => "SJ", "alpha_code3" => "SJM", "numeric_code" => "744", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 215, "name" => "Sweden", "alpha_code2" => "SE", "alpha_code3" => "SWE", "numeric_code" => "752", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 216, "name" => "Switzerland", "alpha_code2" => "CH", "alpha_code3" => "CHE", "numeric_code" => "756", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 217, "name" => "Syrian Arab Republic", "alpha_code2" => "SY", "alpha_code3" => "SYR", "numeric_code" => "760", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 218, "name" => "Taiwan (Province of China)", "alpha_code2" => "TW", "alpha_code3" => "TWN", "numeric_code" => "158", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 219, "name" => "Tajikistan", "alpha_code2" => "TJ", "alpha_code3" => "TJK", "numeric_code" => "762", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 220, "name" => "Tanzania, United Republic of", "alpha_code2" => "TZ", "alpha_code3" => "TZA", "numeric_code" => "834", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 221, "name" => "Thailand", "alpha_code2" => "TH", "alpha_code3" => "THA", "numeric_code" => "764", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 222, "name" => "Timor-Leste", "alpha_code2" => "TL", "alpha_code3" => "TLS", "numeric_code" => "626", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 223, "name" => "Togo", "alpha_code2" => "TG", "alpha_code3" => "TGO", "numeric_code" => "768", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 224, "name" => "Tokelau", "alpha_code2" => "TK", "alpha_code3" => "TKL", "numeric_code" => "772", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 225, "name" => "Tonga", "alpha_code2" => "TO", "alpha_code3" => "TON", "numeric_code" => "776", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 226, "name" => "Trinidad and Tobago", "alpha_code2" => "TT", "alpha_code3" => "TTO", "numeric_code" => "780", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 227, "name" => "Tunisia", "alpha_code2" => "TN", "alpha_code3" => "TUN", "numeric_code" => "788", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 228, "name" => "Turkey", "alpha_code2" => "TR", "alpha_code3" => "TUR", "numeric_code" => "792", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 229, "name" => "Turkmenistan", "alpha_code2" => "TM", "alpha_code3" => "TKM", "numeric_code" => "795", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 230, "name" => "Turks and Caicos Islands", "alpha_code2" => "TC", "alpha_code3" => "TCA", "numeric_code" => "796", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 231, "name" => "Tuvalu", "alpha_code2" => "TV", "alpha_code3" => "TUV", "numeric_code" => "798", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 232, "name" => "Uganda", "alpha_code2" => "UG", "alpha_code3" => "UGA", "numeric_code" => "800", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 233, "name" => "Ukraine", "alpha_code2" => "UA", "alpha_code3" => "UKR", "numeric_code" => "804", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 234, "name" => "United Arab Emirates", "alpha_code2" => "AE", "alpha_code3" => "ARE", "numeric_code" => "784", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 235, "name" => "United Kingdom of Great Britain and Northern Ireland", "alpha_code2" => "GB", "alpha_code3" => "GBR", "numeric_code" => "826", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 236, "name" => "United States Minor Outlying Islands", "alpha_code2" => "UM", "alpha_code3" => "UMI", "numeric_code" => "581", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 237, "name" => "United States of America", "alpha_code2" => "US", "alpha_code3" => "USA", "numeric_code" => "840", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 238, "name" => "Uruguay", "alpha_code2" => "UY", "alpha_code3" => "URY", "numeric_code" => "858", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 239, "name" => "Uzbekistan", "alpha_code2" => "UZ", "alpha_code3" => "UZB", "numeric_code" => "860", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 240, "name" => "Vanuatu", "alpha_code2" => "VU", "alpha_code3" => "VUT", "numeric_code" => "548", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 241, "name" => "Venezuela (Bolivarian Republic of)", "alpha_code2" => "VE", "alpha_code3" => "VEN", "numeric_code" => "862", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 242, "name" => "Viet Nam", "alpha_code2" => "VN", "alpha_code3" => "VNM", "numeric_code" => "704", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 243, "name" => "Virgin Islands (British)", "alpha_code2" => "VG", "alpha_code3" => "VGB", "numeric_code" => "092", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 244, "name" => "Virgin Islands (U.S.)", "alpha_code2" => "VI", "alpha_code3" => "VIR", "numeric_code" => "850", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 245, "name" => "Wallis and Futuna", "alpha_code2" => "WF", "alpha_code3" => "WLF", "numeric_code" => "876", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 246, "name" => "Western Sahara", "alpha_code2" => "EH", "alpha_code3" => "ESH", "numeric_code" => "732", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 247, "name" => "Yemen", "alpha_code2" => "YE", "alpha_code3" => "YEM", "numeric_code" => "887", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 248, "name" => "Zambia", "alpha_code2" => "ZM", "alpha_code3" => "ZMB", "numeric_code" => "894", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 249, "name" => "Zimbabwe", "alpha_code2" => "ZW", "alpha_code3" => "ZWE", "numeric_code" => "716", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ["id" => 250, "name" => "Åland Islands", "alpha_code2" => "AX", "alpha_code3" => "ALA", "numeric_code" => "248", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
